# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
units:
  sp: 14.5 # Padded switch plate size

points:
  zones:
    matrix:
      anchor:
        shift: [00, 00]
      columns:
        inner.key.stagger:
        index.key.stagger: 2
        middle.key.stagger: 9
        ring.key.stagger: -9
        pinky.key:
          stagger: -9
          splay: -8
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_index_home
        shift: [-42, -64]
        rotate: 38
      columns:
        outer.key:
          height: 1u
        home.key:
          height: 1u
          splay: -6
          origin: [-0.5u, -0.5u]
          shift: [0, 4]
        inner.key:
          height: 1u
          splay: -6
          origin: [-0.5u, -0.5u]
      rows:
        thumb:
  rotate: 0

outlines:
  raw:
    - what: rectangle
      where: true
      size: [1u, 1u]
  keys:
    - what: rectangle
      where: true
      size: [1u, 1u]
  board:
    - what: polygon
      fillet: 4
      operation: stack
      points:
        - ref: matrix_inner_top
          shift: [-0.5sp, 0.5sp]
        - ref: thumbfan_outer_thumb
          shift: [-0.5sp, 0.5sp]
        - ref: thumbfan_outer_thumb
          shift: [-0.5sp, -0.5sp]
        - ref: matrix_pinky_bottom
          shift: [0.5sp, -0.5sp]
        - ref: matrix_pinky_top
          shift: [0.5sp, 0.5sp]
        - ref: matrix_middle_top
          shift: [0.5sp, 0.5sp]
        - ref: matrix_middle_top
          shift: [-0.5sp, 0.5sp]


pcbs:
  heartstopper:
    footprints:
      diodes:
        what: diode
        where: true
        params:
          from: "{{clique_src}}"
          to: "{{switch}}"

      keys:
        what: mx
        where: true
        params:
          from: "{{switch}}"
          to: "{{clique_dst}}"
          reverse: true
          keycaps: true
          hotswap: true

      mcu:
        what: promicro
        where:
          - ref: matrix_inner_home
            shift: [-1U, 0]
            rotate: -90
        params:
          reverse: true
